# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  datasource:
        #name: devtest
        url: jdbc:mysql://43.254.53.219:3336/shirotest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
        username: root
        password: root
  
logging:
  level:
    ROOT: info
